In [19]:
import numpy
n = numpy.arange(27)
# n

In [18]:
# n.reshape(3,3,3)

In [22]:
import cv2

In [30]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [35]:
im_g[0:2, 2:4]
# im_g.shape
# im_g[2,4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [37]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [39]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [44]:
ims=numpy.hstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [46]:
ims=numpy.vstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [54]:
lst=numpy.vsplit(ims,3)
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)